package com.example.healthsystem.service;

import com.example.healthsystem.model.Consultation;
import com.example.healthsystem.model.Docteur;
import com.example.healthsystem.model.UserType;
import com.example.healthsystem.repository.ConsultationRepository;
import com.example.healthsystem.repository.DocteurRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

@Service
public class DocteurService {

    private final DocteurRepository docteurRepository;
    private final ConsultationRepository consultationRepository;

    @Autowired
    public DocteurService(DocteurRepository docteurRepository, ConsultationRepository consultationRepository) {
        this.docteurRepository = docteurRepository;
        this.consultationRepository = consultationRepository;
    }


    public List<Docteur> getDoctors() {
        return docteurRepository.findAll();
    }
    public List<Docteur> getDoctorsBySpeciality(String speciality) { return docteurRepository.findBySpecialiteDocteur(speciality); }

    public Docteur saveDocteur(Docteur docteur) {
        return docteurRepository.save(docteur);
    }

    public List<Docteur> getAllDocteurs() {
        return docteurRepository.findAll();
    }

    public Optional<Docteur> getDocteurById(Long id) {
        return docteurRepository.findById(id);
    }

    public void deleteDocteur(Long id) {
        if (docteurRepository.existsById(id)) {
            docteurRepository.deleteById(id);
        } else {
            throw new RuntimeException("Docteur with ID " + id + " does not exist.");
        }
    }

    public Consultation addConsultation(Long docteurId, Consultation consultation) {
        Optional<Docteur> docteurOpt = docteurRepository.findById(docteurId);
        if (docteurOpt.isPresent()) {
            Docteur docteur = docteurOpt.get();
            consultation.setDocteurService(docteur);
            return consultationRepository.save(consultation);
        } else {
            throw new RuntimeException("Docteur with ID " + docteurId + " does not exist.");
        }
    }

    public List<Consultation> getConsultationsByDocteur(Long docteurId) {
        Optional<Docteur> docteurOpt = docteurRepository.findById(docteurId);
        if (docteurOpt.isPresent()) {
            return docteurOpt.get().getConsultations();
        } else {
            throw new RuntimeException("Docteur with ID " + docteurId + " does not exist.");
        }
    }

    public void removeConsultation(Long consultationId) {
        if (consultationRepository.existsById(consultationId)) {
            consultationRepository.deleteById(consultationId);
        } else {
            throw new RuntimeException("Consultation with ID " + consultationId + " does not exist.");
        }
    }

    public void removeAll(){
        docteurRepository.deleteAll();
    }

    public void initiateDocteurListe() {
    }

//    public void initiateDocteurListe() {
//        List<Docteur> docteurs = new ArrayList<>();
//
//        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
//
//        docteurs.add(new Docteur(
//                null, // ID is autogenerated
//                "Dr. John Smith",
//                "john.smith@example.com",
//                "+212600000001",
//                UserType.DOCTOR,
//                LocalDate.parse("1980-05-15", dateFormatter),
//                "Cardiologie"
//        ));
//
//        docteurs.add(new Docteur(
//                null,
//                "Dr. Jane Doe",
//                "jane.doe@example.com",
//                "+212600000002",
//                UserType.DOCTOR,
//                LocalDate.parse("1985-08-20", dateFormatter),
//                "Neurologie"
//        ));
//
//        docteurs.add(new Docteur(
//                null,
//                "Dr. Ahmed Benomar",
//                "ahmed.benomar@example.com",
//                "+212600000003",
//                UserType.DOCTOR,
//                LocalDate.parse("1978-12-10", dateFormatter),
//                "Orthopédie"
//        ));
//
//        docteurs.add(new Docteur(
//                null,
//                "Dr. Fatima Zahra El Fassi",
//                "fatima.zahra@example.com",
//                "+212600000004",
//                UserType.DOCTOR,
//                LocalDate.parse("1990-07-07", dateFormatter),
//                "Pédiatrie"
//        ));
//
//        docteurs.add(new Docteur(
//                null,
//                "Dr. Michael Brown",
//                "michael.brown@example.com",
//                "+212600000005",
//                UserType.DOCTOR,
//                LocalDate.parse("1982-03-25", dateFormatter),
//                "Dermatologie"
//        ));
//
//        docteurs.add(new Docteur(
//                null,
//                "Dr. Sarah Lee",
//                "sarah.lee@example.com",
//                "+212600000006",
//                UserType.DOCTOR,
//                LocalDate.parse("1989-01-30", dateFormatter),
//                "Oncologie"
//        ));
//
//        docteurs.add(new Docteur(
//                null,
//                "Dr. Youssef Amrani",
//                "youssef.amrani@example.com",
//                "+212600000007",
//                UserType.DOCTOR,
//                LocalDate.parse("1975-11-12", dateFormatter),
//                "Ophtalmologie"
//        ));
//
//        docteurs.add(new Docteur(
//                null,
//                "Dr. Sofia Haddad",
//                "sofia.haddad@example.com",
//                "+212600000008",
//                UserType.DOCTOR,
//                LocalDate.parse("1993-04-18", dateFormatter),
//                "Gynécologie"
//        ));
//
//        docteurs.add(new Docteur(
//                null,
//                "Dr. William Johnson",
//                "william.johnson@example.com",
//                "+212600000009",
//                UserType.DOCTOR,
//                LocalDate.parse("1986-09-05", dateFormatter),
//                "Radiologie"
//        ));
//
//        docteurs.add(new Docteur(
//                null,
//                "Dr. Amina Kabbaj",
//                "amina.kabbaj@example.com",
//                "+212600000010",
//                UserType.DOCTOR,
//                LocalDate.parse("1995-06-22", dateFormatter),
//                "Psychiatrie"
//        ));
//
//        // Save all doctors to the database
//        docteurRepository.saveAll(docteurs);
//    }
}




